version: '3.7'

services:
  jenkins:
    restart: always
    container_name: jenkins-me
    image: jenkins/jenkins:latest
    ports:
      - 38088:8080
    volumes:
      - ./docker/jenkins/home:/var/jenkins_home
      # TODO mount to s3
      # - /Volumes/nas52/desktop/jenkins/home:/var/jenkins_home